import React from 'react'

export const metadata = {
    title: 'Login',
    description: 'Generated by create next app',
  }

const Login = () => {
  return (
    <Container>

      
    </Container>
  )
}

export default Login
